"""Org settings, part C: Security, Third-party Access, Integrations, Archive, Developer settings."""
from dsl import *
from org_a import BASE

ENABLE = ["Enable all", "Disable all"]

security = G("o-g-security", "Security", [
    P("o-auth-security", "Authentication security", f"{BASE}/security", "shield-lock", [
        S("Two-factor authentication", [
            CB("Require two-factor authentication for everyone in the octo-sample-org organization", "Members, billing managers, and outside collaborators who do not have two-factor authentication enabled for their personal account will be removed from the organization and will receive an email notifying them about the change."),
        ]),
        S("SAML single sign-on", [
            CB("Enable SAML authentication", "Enable SAML authentication for your organization through an identity provider like Azure, Okta, OneLogin, Ping Identity or your custom SAML 2.0 provider."),
            T("Sign on URL", "Members will be forwarded here when signing in to your organization.", placeholder="https://yourapp.example.com/apps/appId"),
            T("Issuer", "Typically a unique URL generated by your SAML identity provider."),
            TA("Public certificate", "Paste your x509 certificate here."),
            CB("Require SAML SSO authentication for all members of the octo-sample-org organization", "Members will be required to authenticate through your identity provider."),
        ]),
        S("IP allow list", [
            CB("Enable IP allow list", "Only IP addresses in the list below may access resources owned by this organization."),
            CB("Allow access by GitHub Apps", "Include IP addresses from installed GitHub Apps in the allow list."),
            L("IP allow list entries", ["203.0.113.0/24 · Office VPN"]),
        ]),
        S("SSH certificate authorities", [
            L("SSH certificate authorities", [], "With SSH certificate authorities, members can access organization repositories over SSH using SSH certificates you provide."),
            B("New CA"),
            CB("Require SSH Certificates", "Only allow SSH access to repositories via SSH certificates signed by these CAs."),
        ]),
    ]),
    P("o-ghas-configurations", "Advanced Security · Configurations", f"{BASE}/security_products/configurations", "shield-check", [
        S("Security configurations", [
            L("Security configurations", ["GitHub recommended · 23 repositories", "Strict (custom) · 4 repositories"], "Security configurations are collections of enablement settings for GitHub's security features that can be applied to repositories."),
            B("New configuration"),
            B("Apply to", "Apply a configuration to all or selected repositories."),
        ]),
        S("Configuration settings", [
            SEL("Dependency graph", ["Enabled", "Disabled", "Not set"]),
            SEL("Dependabot alerts", ["Enabled", "Disabled", "Not set"]),
            SEL("Dependabot security updates", ["Enabled", "Disabled", "Not set"]),
            SEL("Code scanning default setup", ["Enabled", "Disabled", "Not set"]),
            SEL("Secret scanning", ["Enabled", "Disabled", "Not set"]),
            SEL("Push protection", ["Enabled", "Disabled", "Not set"], "Block commits that contain supported secrets."),
            SEL("Private vulnerability reporting", ["Enabled", "Disabled", "Not set"]),
            SEL("Enforce configuration", ["Don't enforce", "Enforce"], "Prevent repository admins from changing these settings."),
        ]),
    ]),
    P("o-ghas-global", "Advanced Security · Global settings", f"{BASE}/security_products/global_settings", "shield-check", [
        S("Dependabot", [
            CB("Grouped security updates", "Groups all available updates that resolve a Dependabot alert into one pull request."),
            CB("Dependabot on Actions runners", "Run Dependabot security and version updates on Actions runners.", True),
            CB("Dependabot on self-hosted runners"),
            L("Dependabot rules", ["Dismiss low impact alerts for development-scoped dependencies"], "Auto-triage rules for Dependabot alerts."),
        ]),
        S("Code scanning", [
            CB("Recommend the extended query suite for repositories enabling default setup"),
            SEL("Copilot Autofix", ["On", "Off"], "Suggest fixes for CodeQL alerts using Copilot Autofix."),
            SEL("Check runs failure threshold", ["High or higher / Only errors", "Critical / Errors and warnings", "None"], "Choose which security alert severities cause a pull request check to fail."),
        ]),
        S("Secret scanning", [
            CB("Add a resource link in the CLI and web UI when a commit is blocked", "Provide a link to your internal guidance when push protection blocks a commit."),
            L("Custom patterns", ["internal-api-key · Published"], "Define your own secret patterns to scan for."),
            B("New pattern"),
        ]),
    ]),
    P("o-deploy-keys", "Deploy keys", f"{BASE}/deploy_keys", "key", [
        S("Deploy keys", [
            CB("Allow deploy keys", "Deploy keys can be added to repositories in this organization. Disabling this will disable existing deploy keys.", True),
            I("Deploy keys are added in each repository's settings", "Deploy keys grant access to a single repository. Add them under the repository's Settings › Deploy keys."),
        ]),
    ]),
    P("o-compliance", "Compliance", f"{BASE}/compliance", "checklist", [
        S("Compliance reports", [
            L("Reports", ["SOC 1, Type 2", "SOC 2, Type 2", "ISO/IEC 27001:2013 certificate", "Cloud Security Alliance CAIQ"], "Download GitHub's compliance reports."),
        ]),
    ]),
    P("o-domains", "Verified and approved domains", f"{BASE}/domains", "verified", [
        S("Verified & approved domains", [
            L("Domains", ["octo.example.invalid · Verified"], "Verify or approve domains to show a Verified badge and route email notifications only to addresses on those domains."),
            B("Add a domain"),
            CB("Restrict email notifications to only approved or verified domains", "Members will only receive email notifications about the organization at addresses on these domains."),
        ]),
    ]),
    P("o-secrets-actions", "Secrets and variables · Actions", f"{BASE}/secrets/actions", "lock", [
        S("Actions secrets and variables", [
            L("Organization secrets", ["NPM_TOKEN · Private repositories", "DEPLOY_KEY · 3 selected repositories"], "Secrets are encrypted and are used for sensitive data. Anyone with collaborator access to the repositories with access to each secret can use it for Actions."),
            B("New organization secret"),
            L("Organization variables", ["NODE_VERSION = 22"], "Variables are shown as plain text and are used for non-sensitive data."),
            B("New organization variable"),
            R("Repository access", ["Public repositories", "Private repositories", "Selected repositories"]),
        ]),
    ]),
    P("o-secrets-codespaces", "Secrets and variables · Codespaces", f"{BASE}/secrets/codespaces", "lock", [
        S("Codespaces secrets", [
            L("Organization secrets", ["DB_PASSWORD · 2 selected repositories"], "Development environment secrets are exposed as environment variables in codespaces."),
            B("New organization secret"),
        ]),
    ]),
    P("o-secrets-dependabot", "Secrets and variables · Dependabot", f"{BASE}/secrets/dependabot", "lock", [
        S("Dependabot secrets", [
            L("Organization secrets", ["PRIVATE_REGISTRY_TOKEN"], "Secrets are available to Dependabot, e.g. to access private package registries."),
            B("New organization secret"),
        ]),
    ]),
])

third_party = G("o-g-third-party", "Third-party Access", [
    P("o-github-apps", "GitHub Apps", f"{BASE}/installations", "apps", [
        S("Installed GitHub Apps", [
            L("Installed GitHub Apps", ["Netlify · All repositories", "Codecov · 6 repositories"], "GitHub Apps augment and extend your workflows on GitHub with commercially supported tools, and they act with the permissions and repository access you grant them."),
            B("Configure"), DB("Uninstall"),
            L("Pending GitHub Apps installation requests", ["Linear · requested by @octo-sample"]),
        ]),
    ]),
    P("o-oauth-policy", "OAuth app policy", f"{BASE}/oauth_application_policy", "apps", [
        S("Third-party application access policy", [
            I("Policy: Access restricted", "Only approved applications can access data in this organization. Applications owned by octo-sample-org always have access."),
            DB("Remove restrictions", "Allow any OAuth app authorized by a member to access the organization's data."),
            L("Approved applications", ["Travis CI · Approved", "Heroku Dashboard · Denied"]),
        ]),
    ]),
    P("o-pat-settings", "Personal access tokens · Settings", f"{BASE}/personal-access-tokens", "key", [
        S("Fine-grained personal access tokens", [
            R("Restrict access via fine-grained personal access tokens", ["Allow access via fine-grained personal access tokens", "Restrict access via fine-grained personal access tokens"], "API and Git access will not be allowed using fine-grained personal access tokens."),
            R("Require administrator approval", ["Require administrator approval", "Do not require administrator approval"], "All access requests by organization members must be approved by an organization owner before the token can be used."),
            SEL("Maximum lifetime for fine-grained tokens", ["No limit", "30 days", "90 days", "366 days"]),
        ]),
        S("Personal access tokens (classic)", [
            R("Restrict personal access tokens (classic) from accessing your organizations", ["Allow access via personal access tokens (classic)", "Restrict access via personal access tokens (classic)"], "API and Git access will not be allowed using personal access tokens (classic)."),
            SEL("Maximum lifetime for personal access tokens (classic)", ["No limit", "30 days", "90 days", "366 days"]),
        ]),
    ]),
    P("o-pat-active", "Personal access tokens · Active tokens", f"{BASE}/personal-access-tokens/active", "key", [
        S("Active tokens", [
            L("Active tokens", ["deploy-script · @octo-sample · Expires Dec 1, 2026"], "Fine-grained tokens with access to this organization."),
            DB("Revoke", "Revoke a member's token access to this organization."),
        ]),
    ]),
    P("o-pat-pending", "Personal access tokens · Pending requests", f"{BASE}/personal-access-token-requests", "key", [
        S("Pending requests", [
            L("Pending requests", ["release-bot token · @octo-ops · Contents: read and write"], "Requests from members for fine-grained tokens to access this organization."),
            B("Approve"), DB("Deny"),
        ]),
    ]),
])

integrations = G("o-g-integrations", "Integrations", [
    P("o-reminders", "Scheduled reminders", f"{BASE}/reminders", "clock", [
        S("Scheduled reminders", [
            I("Scheduled reminders", "Remind teams in Slack about pull requests awaiting review."),
            L("Reminders", ["#eng-reviews · Weekdays 9:00 AM · @backend"]),
            B("Add first reminder"),
        ]),
    ]),
])

archive = G("o-g-archive", "Archive", [
    P("o-audit-log", "Logs · Audit log", f"{BASE}/audit-log", "log", [
        S("Audit log", [
            T("Filter audit log", "Search events like action:repo.destroy or actor:octo-sample.", placeholder="Search audit logs"),
            L("Recent events", ["repo.create · @octo-sample · 1 hour ago", "org.update_member · @octo-ops · yesterday", "protected_branch.update · 3 days ago"], "The audit log lists events triggered by activities that affect your organization."),
            B("Export", "Export as JSON or CSV."),
            B("Export Git events"),
        ]),
    ]),
    P("o-sponsorship-log", "Logs · Sponsorship log", f"{BASE}/sponsors-log", "log", [
        S("Sponsorship log", [L("Sponsorship log", ["Sponsored @maintainer-sample · $100/month"])]),
    ]),
    P("o-deleted-repos", "Deleted repositories", f"{BASE}/deleted_repositories", "trash", [
        S("Deleted repositories", [
            L("Deleted repositories", ["octo-sample-org/legacy-api · Deleted by @octo-sample 5 days ago"], "It may take up to an hour for repositories to be displayed here. You can only restore repositories that are not forks, or have not been forked."),
            B("Restore"),
        ]),
    ]),
])

developer = G("o-g-developer", "", [
    P("o-developer", "Developer settings", f"{BASE}/apps", "code", [
        S("GitHub Apps", [
            L("GitHub Apps", ["octo-release-bot"], "Register GitHub Apps owned by this organization."),
            B("New GitHub App"),
            L("App managers", ["@octo-ops"], "App managers can manage the settings of all GitHub Apps owned by the organization."),
        ]),
        S("OAuth Apps", [L("OAuth Apps", ["octo-sample dashboard"]), B("New OAuth App")]),
    ]),
])
