import Foundation

/// The recreated settings tree, decoded from `Resources/github-{user,org}.json` (generated by `data/*.py`).
struct Catalog: Decodable {
    let scope: String
    let title: String
    let groups: [Group]

    struct Group: Decodable, Identifiable {
        let id: String
        let title: String
        let pages: [Page]
    }

    struct Page: Decodable, Identifiable {
        let id: String
        let title: String
        let path: String
        let icon: String
        /// One sentence on what the page is for (`data/summaries.py`).
        let about: String
        let sections: [Section]

        var controls: [Control] { sections.flatMap(\.controls) }
    }

    struct Section: Decodable {
        let title: String
        let description: String
        let danger: Bool
        let controls: [Control]
    }

    struct Control: Decodable, Identifiable {
        let id: String
        let type: String
        let label: String
        let description: String
        let section: String
    }

    static func load(_ name: String) -> (Catalog, json: String) {
        let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Resources")!
        let data = try! Data(contentsOf: url)
        return (try! JSONDecoder().decode(Catalog.self, from: data), String(decoding: data, as: UTF8.self))
    }
}

extension String {
    func clipped(_ count: Int) -> String {
        self.count <= count ? self : String(prefix(count - 1)) + "…"
    }
}
